#!/bin/bash
# Auto-generated by ISP CRM WireGuard Service
# This file will be automatically updated when subnets are added/removed
# Run this script after WireGuard container restart to restore routes

CONTAINER="isp_crm_wireguard"
INTERFACE="wg0"

# Wait for container to be ready
sleep 2

echo "Routes will be auto-populated when subnets are added in the CRM"
